version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "8080:8080"
        networks: 
            - node-network
        depends_on: 
            - db
        
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8081:8081"

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
           - node-network

networks: 
    node-network:
        driver: bridge   