version: "3.8"
services:
    nodeserver:
        build:
            context: app
        
        command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "30s", "node", "index.js"]    
        container_name: app
        ports:
            - "8080:8080"
        networks: 
            - node-network
        volumes: 
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
        depends_on: 
            - db
        
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8081:8081"
        networks: 
            - node-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
    
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./log:/var/log
            
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
           - node-network

networks: 
    node-network:
        driver: bridge

